PATCHELF ROLLBACK

diff --git a/src/installer/pkg/packaging/snaps/dotnet-sdk-3.1/snap/snapcraft.yaml b/src/installer/pkg/packaging/snaps/dotnet-sdk-3.1/snap/snapcraft.yaml
--- a/src/installer/pkg/packaging/snaps/dotnet-sdk-3.1/snap/snapcraft.yaml
+++ b/src/installer/pkg/packaging/snaps/dotnet-sdk-3.1/snap/snapcraft.yaml
@@ -13,7 +13,7 @@ apps:
     command: dotnet
     environment:
       DOTNET_ROOT: $SNAP # Not required?
-      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH # Required to find libicu in classic.
+      #LD_LIBRARY_PATH: $SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH # Required to find libicu in classic.
 
 parts:
   dotnet-sdk:
@@ -23,7 +23,7 @@ parts:
         - on arm64: https://download.visualstudio.microsoft.com/download/pr/186257d9-bca2-4dda-be74-006205965ec9/b2b63d45482701473d9731abc41ecc2a/dotnet-sdk-3.1.402-linux-arm64.tar.gz
         - on armhf: https://download.visualstudio.microsoft.com/download/pr/8f0dffe3-18f0-4d32-beb0-dbcb9a0d91a1/abe9a34e3f8916478f0bd80402b01b38/dotnet-sdk-3.1.402-linux-arm.tar.gz
 
-      build-attributes: [no-patchelf]
+      #build-attributes: [no-patchelf]
 
       stage-packages:
         - libicu66
@@ -44,33 +44,22 @@ parts:
         patchelf="/snap/snapcraft/current/bin/patchelf"
         base="/snap/core20/current"
 
-        # Snapcraft sets RPATH for all classic executables using patchelf.
-        # With the no-patchelf attribute, we must do this ourselves for the
-        # executables that require it.
-        rpath='$ORIGIN/netcoredeps'
-        rpath="${rpath}:${base}/lib/$SNAPCRAFT_ARCH_TRIPLET"
-        rpath="${rpath}:${base}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
-        rpath="${rpath}:\$ORIGIN/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
+        # Snapcraft sets rpath and rewrites the interpreter to point to the snap base.
+        # Revert this change for the apphost template binaries.
+        for f in $(find "$SNAPCRAFT_PRIME" -name apphost); do
+          # Use original rpath (required?).
+          rpath='$ORIGIN/netcoredeps'
 
-        "${patchelf}" --force-rpath --set-rpath "${rpath}" "${SNAPCRAFT_PRIME}/dotnet"
+          # Sanity check to make sure we are pointing to a valid interpreter.
+          interp="$("${patchelf}" --print-interpreter "${f}" | sed "s|$base||")"
+          if [ ! -f "${interp}" ]; then
+            echo "${interp} not found"
+            exit 1
+          fi
 
-        # Snapcraft sets the interpreter to point to the one found in the base
-        # snap (core18). With the no-patchelf attribute, we must do this
-        # ourselves for the executables that require it.  Do this by querying
-        # the interpreter and prepending the base, if not already patched
-        # by a previous run.
-        interp="$("${patchelf}" --print-interpreter "${SNAPCRAFT_PRIME}/dotnet")"
-        if ! echo "${interp}" | grep -q "${base}"; then
-          interp="${base}${interp}"
-        fi
-
-        # Sanity check to make sure we are pointing to a valid interpreter.
-        if [ ! -f "${interp}" ]; then
-          echo "${interp} not found"
-          exit 1
-        fi
-
-        "${patchelf}" --set-interpreter "${interp}" "${SNAPCRAFT_PRIME}/dotnet"
+          #"${patchelf}" --force-rpath --set-rpath "${rpath}" "${f}"
+          #"${patchelf}" --set-interpreter "${interp}" "${f}"
+        done
 
   runtime-wrapper:
       plugin: dump
