snap packaging: uprev dotnet-sdk, move to core20, and various fixes
- uprev .NET SDK to 3.1.402

- migrate snap base to core20

- enable for all published architectures (amd64, arm64, armhf)

Snapcraft supports "advanced grammar" to selectively configure some
aspects of the snapcraft.yaml based on the target architecture.
Unfortunately this does not currently support `source-checksum`
property to fully verify the fetched sources.  This aspect is on the
Snapcraft road to address, but may not be an issue for the real build
infrastructure.

- manually patch 3.1 SDK dotnet rpath & interpreter to the correct paths

Snapcraft automatically patches the rpath and interpreter for all executables
found within a snap.  However, this impacts the `apphost` template binaries,
resulting in some unexpected behaviors and crashes, e.g.:
`*** stack smashing detected ***: terminated`

Disable Snapcraft's automatic patching using the 'no-patchelf' build-attribute,
but then patch the `dotnet` binary to ensure it works properly as a classic
app.

- test script used on Ubuntu 20.04, 16.04 and Fedora 32:

```
#!/bin/bash -ex

dotnet="/snap/bin/dotnet-sdk.dotnet"
rm -rf apptest

# Create .NET sample project "apptest".
$dotnet new console -n apptest

# Build project.
$dotnet build apptest

# Run project using `dotnet run`.
$dotnet run --project apptest

# Run project using built "dll" via `dotnet`.
$dotnet ./apptest/bin/Debug/netcoreapp3.1/apptest.dll

# Run project using built binary.  Requires:
# (1) DOTNET_ROOT for 'Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.'
# (2) LD_LIBRARY_PATH for 'A fatal error occurred. The required library libhostfxr.so could not be found.'
LD_LIBRARY_PATH=/snap/dotnet-sdk/current/usr/lib/x86_64-linux-gnu DOTNET_ROOT=/snap/dotnet-sdk/current ./apptest/bin/Debug/netcoreapp3.1/apptest

# Publish self-contained build.
$dotnet publish apptest  --self-contained -r linux-x64

# Run self-contained build binary.
./apptest/bin/Debug/netcoreapp3.1/linux-x64/publish/apptest

# Run self-contained "dll" via `dotnet`.
$dotnet ./apptest/bin/Debug/netcoreapp3.1/linux-x64/publish/apptest.dll
```

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

# Please enter the commit message for your changes. Lines starting
# with '#' will be kept; you may remove them yourself if you want to.
# An empty message aborts the commit.
#
# Date:      Tue Sep 8 13:29:27 2020 -0400
#
# On branch exp1
# Changes to be committed:
#	modified:   snap/snapcraft.yaml
#
# Untracked files:
#	dotnet-sdk_amd64.txt
#	dotnet-sdk_arm64.txt
#	dotnet-sdk_armhf.txt
#

diff --git a/src/installer/pkg/packaging/snaps/dotnet-sdk-3.1/snap/snapcraft.yaml b/src/installer/pkg/packaging/snaps/dotnet-sdk-3.1/snap/snapcraft.yaml
--- a/src/installer/pkg/packaging/snaps/dotnet-sdk-3.1/snap/snapcraft.yaml
+++ b/src/installer/pkg/packaging/snaps/dotnet-sdk-3.1/snap/snapcraft.yaml
@@ -1,27 +1,34 @@
 name: dotnet-sdk
-version: 3.1.200
+version: 3.1.402
 summary: Cross-Platform .NET Core SDK
 description: |
   .NET Core SDK. https://dot.net/core.
 
 grade: stable
 confinement: classic
+base: core20
 
 apps:
   dotnet:
     command: dotnet
-
-base: core18
+    environment:
+      DOTNET_ROOT: $SNAP # Not required?
+      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH # Required to find libicu in classic.
 
 parts:
   dotnet-sdk:
       plugin: dump
-      source: https://download.visualstudio.microsoft.com/download/pr/daec2daf-b458-4ae1-9046-b8ba09b5fb49/733e2d73b41640d6e6bdf1cc6b9ef03b/dotnet-sdk-3.1.200-linux-x64.tar.gz
-      source-checksum: sha512/5b9398c7bfe7f67cd9f38fdd4e6e429e1b6aaac0fe04672be0f8dca26580fb46906fd1d2deea6a7d3fb07d77e898f067d3ac1805fe077dc7c1adf9515c9bc9a9
+      source:
+        - on amd64: https://download.visualstudio.microsoft.com/download/pr/f01e3d97-c1c3-4635-bc77-0c893be36820/6ec6acabc22468c6cc68b61625b14a7d/dotnet-sdk-3.1.402-linux-x64.tar.gz
+        - on arm64: https://download.visualstudio.microsoft.com/download/pr/186257d9-bca2-4dda-be74-006205965ec9/b2b63d45482701473d9731abc41ecc2a/dotnet-sdk-3.1.402-linux-arm64.tar.gz
+        - on armhf: https://download.visualstudio.microsoft.com/download/pr/8f0dffe3-18f0-4d32-beb0-dbcb9a0d91a1/abe9a34e3f8916478f0bd80402b01b38/dotnet-sdk-3.1.402-linux-arm.tar.gz
+
+      build-attributes: [no-patchelf]
+
       stage-packages:
-        - libicu60
-        - libssl1.0.0
-        - libcurl3
+        - libicu66
+        - libssl1.1
+        - libcurl4
         - libgssapi-krb5-2
         - libstdc++6
         - zlib1g
@@ -29,6 +36,41 @@ parts:
         - libtinfo5
         - liblttng-ust0
         - liburcu6
+
+      override-prime: |
+        set -x
+        snapcraftctl prime
+
+        patchelf="/snap/snapcraft/current/bin/patchelf"
+        base="/snap/core20/current"
+
+        # Snapcraft sets RPATH for all classic executables using patchelf.
+        # With the no-patchelf attribute, we must do this ourselves for the
+        # executables that require it.
+        rpath='$ORIGIN/netcoredeps'
+        rpath="${rpath}:${base}/lib/$SNAPCRAFT_ARCH_TRIPLET"
+        rpath="${rpath}:${base}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
+        rpath="${rpath}:\$ORIGIN/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
+
+        "${patchelf}" --force-rpath --set-rpath "${rpath}" "${SNAPCRAFT_PRIME}/dotnet"
+
+        # Snapcraft sets the interpreter to point to the one found in the base
+        # snap (core18). With the no-patchelf attribute, we must do this
+        # ourselves for the executables that require it.  Do this by querying
+        # the interpreter and prepending the base, if not already patched
+        # by a previous run.
+        interp="$("${patchelf}" --print-interpreter "${SNAPCRAFT_PRIME}/dotnet")"
+        if ! echo "${interp}" | grep -q "${base}"; then
+          interp="${base}${interp}"
+        fi
+
+        # Sanity check to make sure we are pointing to a valid interpreter.
+        if [ ! -f "${interp}" ]; then
+          echo "${interp} not found"
+          exit 1
+        fi
+
+        "${patchelf}" --set-interpreter "${interp}" "${SNAPCRAFT_PRIME}/dotnet"
 
   runtime-wrapper:
       plugin: dump
